[Draft] anniv meta
ProjectAnni/book pull request #12
Opened 2021-12-15 11:35 UTC by SeraphJACK

2021-12-15 12:04 UTC, Last-Order approved these changes

2021-12-15 14:22 UTC, Last-Order approved these changes

2021-12-15 14:22 UTC, Last-Order commented on src/06.anniv/09.search.md
> +| `album`   | `bool`   | 是否搜索专辑 |
`search_albums` ，下同，不然有点歧义

2021-12-15 14:22 UTC, Last-Order commented on src/06.anniv/09.search.md
> +`POST /api/search`
GET，`boolean`的参数有任意值就认为`true`就行了

2021-12-15 14:52 UTC, Yesterday17 requested changes

2021-12-15 14:52 UTC, Yesterday17 commented on src/06.anniv/09.search.md
> +  albums: AlbumInfo[];
三个返回应该都是 `?:`

2021-12-15 14:52 UTC, Yesterday17 commented on src/06.anniv/09.search.md
> +  playlists: Playlist[];
这里需要返回 `Playlist` 的全部内容吗？比如 `songs`：

```ts
interface Playlist {
  //...
  songs: PlaylistSongWithId[];
}
```

2021-12-15 14:52 UTC, Yesterday17 commented on src/06.anniv/09.search.md
> +| `902002` | 用户未登录 |
搜索需要用户登录吗

2021-12-15 14:52 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +`GET /api/meta/tags`
需要补充描述一下需不需要用户登录，下同。

2021-12-15 17:14 UTC, Yesterday17 requested changes

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +返回 `AlbumInfo[]` 。
```suggestion
### 返回

`AlbumInfo[]`
```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +# 专辑元数据
增加的新页面需要同步到 `SUMMARY.md` 中，下页同。

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +`Anniv` 对 repo 元数据进行索引以及封装。此章节接口均需要用户登录。
```suggestion
`Anniv` 提供对元数据仓库中元数据进行索引的能力。对应的接口需要用户登录。
```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +## Tag 列表
```suggestion
## 获取 Tag 列表
```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +返回 `string[]` 。
```suggestion
返回包含所有 `Tag` 的数组，类型为 `string[]` 。
```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +支持同时请求多个专辑信息。
```suggestion
通过 `album_id` 获得专辑元数据的接口。支持同时获取多张专辑的元数据信息。
```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +`GET /api/meta/album?id[]=...&id[]=...&...`
```suggestion
`GET /api/meta/album`
```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +| `id`   | 专辑 ID |
```suggestion
| `id[]`   | 待获取元数据的专辑 `ID` 列表 |
```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +返回 `Record<String, AlbumInfo | null>` 。
```suggestion
返回以 `album_id` 为键，专辑元数据或空为值的 `Object`。
```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +其中，键为 `album_id` 。查询成功的，对应值为 `AlbumInfo` ，否则为 `null` 。
```suggestion
当查询成功时，值为专辑的 `AlbumInfo`，否则为 `null`。

类型表示为 `Record<String, AlbumInfo | null>`。
```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/09.search.md
> +需要用户登录。
```suggestion
```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/09.search.md
> +
```suggestion
该接口需要用户登录。

```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/09.search.md
> +
```suggestion
### 参数列表

```

2021-12-15 17:14 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +
错误列表，下同。

2021-12-15 17:22 UTC, Last-Order approved these changes

2021-12-16 03:18 UTC, Yesterday17 requested changes

2021-12-16 03:18 UTC, Yesterday17 commented on src/06.anniv/09.search.md
> +| `902000` | 内容不存在 |
结果为空不应该是错误吧。这么看来上面那三个还是用 `:` 比 `?:` 更好。

2021-12-16 04:46 UTC, Yesterday17 approved these changes

2021-12-16 04:46 UTC, Yesterday17 commented on src/06.anniv/08.meta.md
> +| `902000` | `Tag` 不存在 |
`Tag` 不存在返回的应该是空数组而不是错误吧（？）不大好说

2021-12-16 05:46 UTC, merged