feat(anniv): favourite
ProjectAnni/book pull request #17
Opened 2021-12-18 15:05 UTC by SeraphJACK

2021-12-18 15:16 UTC, Yesterday17 requested changes

2021-12-18 15:16 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +| `902000` | 单曲不存在 |
这里是不是可以透明地不返回错误？

2021-12-18 15:16 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +| `music` | `FavouriteListInfo` | 需要删除的列表 |
同上

2021-12-18 15:16 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +### 获取喜欢列表
```suggestion
### 获取全部已订阅的播放列表
```

2021-12-18 15:16 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +## 播放列表
```suggestion
## 订阅播放列表
```

2021-12-18 15:16 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +  list_id: string;
`owner` 和 `cover` 之类的也可以返回一下？这样点进去之前就不需要加载内容了。

2021-12-18 15:16 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +| `music` | `FavouriteListInfo` | 需要添加的单曲 |
~~复制没改？~~

2021-12-18 15:16 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +### 添加单曲
订阅播放列表

2021-12-18 15:16 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +| `902004` | 列表已存在 |
```suggestion
| `902004` | 列表已订阅 |
```

2021-12-18 15:16 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +### 删除单曲
```suggestion
### 取消订阅
```

2021-12-18 15:16 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +| `902000` | 列表不存在 |
```suggestion
| `902000` | 列表未订阅 |
```

同上，这里的错误是否也可以透明？

2021-12-18 15:29 UTC, SeraphJACK commented on src/06.anniv/10.favorite.md
> +| `music` | `FavouriteListInfo` | 需要添加的单曲 |
确实（

2021-12-18 15:32 UTC, SeraphJACK commented on src/06.anniv/10.favorite.md
> +| `music` | `FavouriteListInfo` | 需要删除的列表 |
什么同上

2021-12-18 15:34 UTC, SeraphJACK commented on src/06.anniv/10.favorite.md
> +  list_id: string;
没有 cover 来着（

2021-12-18 15:37 UTC, SeraphJACK commented on src/06.anniv/10.favorite.md
> +  list_id: string;
owner 和 name 都加进去了

2021-12-18 15:38 UTC, Yesterday17 requested changes

2021-12-18 15:38 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +interface FavouriteMusicInfo {
这结构是不是能单独弄成 `MusicIndex` 放在 `00` 里了（

2021-12-18 15:38 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +`POST /api/favourite/music`
`PUT`？

2021-12-18 15:38 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +| `music` | `FavouriteMusicInfo` | 需要添加的单曲 |
这看上去就很
```json
{
  "music": {
    "album_id": "xxx"
    // ...
  }
}
```

2021-12-18 15:38 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +`POST /api/favourite/list`
这里 `playlist` 还是不要简写吧，下面的参数也是。

2021-12-18 15:45 UTC, SeraphJACK commented on src/06.anniv/10.favorite.md
> +interface FavouriteMusicInfo {
无所谓吧，读了知道是啥就行了（

2021-12-18 16:15 UTC, Yesterday17 approved these changes

2021-12-19 00:27 UTC, merged

2021-12-19 00:28 UTC, SeraphJACK commented
不对啊，忘记加 summary 了