[Draft] Annil 歌词分发
ProjectAnni/book pull request #2
Opened 2021-12-03 15:47 UTC by SeraphJACK

2021-12-03 16:17 UTC, Yesterday17 requested changes

2021-12-03 16:17 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
> +获得歌词的 `API` 定义为 `GET /{catalog}/{track_id}/lyrics`
复数？

2021-12-03 16:17 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
> +<!--TODO 更新版本信息-->
别 `TODO` 了，把下面日期和版本改了（

2021-12-03 16:17 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
>  协议版本：0.1.2
`0.1.3-DRAFT`

2021-12-03 16:17 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
> +### 歌词分发
`### 歌词分发 【Draft】`

2021-12-03 16:17 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
> +每首歌的歌词有许多翻译，以下参数用于表示所请求的歌词翻译。
音轨的歌词可能存在复数中翻译，可以通过以下参数请求特定语言的歌词。

2021-12-03 16:17 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
> +其中，留空代表不翻译。其他代码代表对应语言翻译，语言代码的使用参考 [RFC5646][rfc5646] 标准。
当 `lang` 参数留空时，表示请求未翻译的原文。否则则请求指定语言的歌词，...

2021-12-03 16:17 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
> +获得歌词的 `API` 定义为 `GET /{catalog}/{track_id}/lyrics`
或许 `/{catalog}/{track_id}/lyric/{lang}` 更加合适？

2021-12-03 16:17 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
> +#### 歌曲语言信息
这个 `API` 应该更靠前（

2021-12-03 16:17 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
> +可以通过 `GET /{catalog}/{track_id}/lyrics/lang` 获取歌词的原生语言与可选翻译列表。
Maybe `/{catalog}/{track_id}/lyrics`?

这里的语义可以是复数，也可以和另一个的 `/lyric` 区分开。

2021-12-03 16:17 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
> +| `lang`      | 歌曲原生语言 |
`lang` 感觉好怪 :em198:

2021-12-03 16:19 UTC, SeraphJACK commented on src/05.audio-library/01.protocol.md
> +获得歌词的 `API` 定义为 `GET /{catalog}/{track_id}/lyrics`
为什么 lang 是参数啊。这里是用来获取歌曲本身的语言以及可用的翻译语言列表的。

2021-12-03 16:24 UTC, SeraphJACK commented on src/05.audio-library/01.protocol.md
> +| `lang`      | 歌曲原生语言 |
那叫什么，`native` 吗（

2021-12-03 16:31 UTC, SeraphJACK commented
有一个问题，对于没有任何歌词语言信息的 track ，`GET /{catalog}/{track_id}/lyrics` 是不是应该返回 `404` 。

2021-12-03 16:36 UTC, SeraphJACK commented on src/05.audio-library/01.protocol.md
> +获得歌词的 `API` 定义为 `GET /{catalog}/{track_id}/lyrics`
感觉还是用 param 更合适一些。TBD

2021-12-04 10:26 UTC, Yesterday17 approved these changes

2021-12-04 10:26 UTC, merged