rua
ProjectAnni/book pull request #29
Opened 2021-12-25 14:54 UTC by SeraphJACK

2021-12-25 14:55 UTC, Yesterday17 requested changes

2021-12-25 14:55 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +  album_title?: string;
不如加到 TrackInfo 里？

2021-12-25 14:56 UTC, SeraphJACK commented on src/06.anniv/10.favorite.md
> +  album_title?: string;
实现都写完了（

2021-12-25 14:57 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +  album_title?: string;
但放在这里很怪啊

2021-12-25 14:57 UTC, SeraphJACK commented on src/06.anniv/10.favorite.md
> +  album_title?: string;
确实，应该加 TrackInfo 里的

2021-12-25 15:05 UTC, SeraphJACK commented
还是不对啊，放 `TrackInfo` 里也很怪啊

2021-12-25 15:05 UTC, Yesterday17 requested changes

2021-12-25 15:05 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
>    disc_id: number;
那这里的返回直接用 `TrackInfoWithAlbum` 就行了。现在 `TrackInfo` 里还是没有 album_title 的。

2021-12-26 06:21 UTC, Yesterday17 approved these changes

2021-12-27 08:21 UTC, merged