元数据仓库 v1.3
ProjectAnni/book pull request #46
Opened 2022-03-08 05:11 UTC by Yesterday17

2022-03-08 06:04 UTC, tuzi3040 submitted a review, later dismissed

2022-03-08 13:57 UTC, Yesterday17 commented
@SeraphJACK 用目录的话怎么弄（

2022-03-09 06:13 UTC, tuzi3040 requested changes

2022-03-09 06:13 UTC, tuzi3040 commented on src/02.metadata-repository/07.repo-merge.md
> +`Tag` 合并时，取两方 `Tag` 的并集。`Tag` 的命名遵循下文 Tag 合并的策略。
```suggestion
`Tag` 合并时，取 `Tag` 的并集。
```

2022-03-09 06:13 UTC, tuzi3040 commented on src/02.metadata-repository/07.repo-merge.md
> +
```suggestion
```

2022-03-09 06:13 UTC, tuzi3040 commented on src/02.metadata-repository/07.repo-merge.md
> +基本原则是：对同名的 Tag，认为其就是相同的；对名称不同的 Tag，进行合并。
```suggestion
合并时，按照 Tag 的名称进行合并，将两棵 Tag 树合并为一张有向 Tag 图。
```

2022-03-09 06:13 UTC, tuzi3040 commented on src/02.metadata-repository/07.repo-merge.md
> +在合并完成后，两棵 Tag 树合并为一张 Tag 图。图中不能出现环路，当出现环时合并失败，需要人工介入。
```suggestion
合并完成后，该有向图中不能出现环路，当出现环时合并失败，需要人工介入。
```

2022-03-09 06:26 UTC, tuzi3040 submitted a review, later dismissed

2022-03-10 03:26 UTC, tuzi3040 approved these changes

2022-03-17 18:15 UTC, merged