规范化 Annil 对 Range 的支持方式
ProjectAnni/book pull request #48
Opened 2022-03-20 13:43 UTC by Yesterday17

2022-03-20 16:17 UTC, SeraphJACK requested changes

2022-03-20 16:17 UTC, SeraphJACK commented on src/05.audio-library/01.protocol.md
> +| `X-Audio-Bitrate`    | 音频的实际音质，可选值为  `low`、`medium`、`high`、`lossless`      |
如果是 `low`, `medium`, `high`, `lossless` 这样的用 `X-Audio-Quality` 比较符合语义吧

2022-03-20 16:20 UTC, Yesterday17 commented on src/05.audio-library/01.protocol.md
> +| `X-Audio-Bitrate`    | 音频的实际音质，可选值为  `low`、`medium`、`high`、`lossless`      |
那上面的 prefer_bitrate 是不是也改成 prefer_quality 比较好？

2022-03-20 16:56 UTC, SeraphJACK commented on src/05.audio-library/01.protocol.md
> +| `X-Audio-Bitrate`    | 音频的实际音质，可选值为  `low`、`medium`、`high`、`lossless`      |
确实

2022-03-20 16:56 UTC, SeraphJACK commented on src/05.audio-library/01.protocol.md
> +| `X-Audio-Bitrate`    | 音频的实际音质，可选值为  `low`、`medium`、`high`、`lossless`      |
`bitrate` 语义上来说应该是类似 `128 kbps` `320 kbps` 这种

2022-03-21 03:23 UTC, SeraphJACK approved these changes

2022-03-21 03:24 UTC, merged