修改播放列表本身的信息
ProjectAnni/book pull request #49
Opened 2022-03-20 14:08 UTC by Yesterday17

2022-03-20 15:06 UTC, Last-Order requested changes

2022-03-20 15:06 UTC, Last-Order commented on src/06.anniv/03.playlist.md
> +| `command` | `string` | 表示修改的类型，可选项为 `append`、`remove`、`reorder` 或 `replace` |
`info`呢

2022-03-20 16:19 UTC, SeraphJACK approved these changes

2022-03-21 02:46 UTC, Last-Order approved these changes

2022-03-21 03:13 UTC, merged