Tag 类型
ProjectAnni/book pull request #51
Opened 2022-03-27 05:04 UTC by Yesterday17

2022-03-27 06:49 UTC, tuzi3040 submitted a review, later dismissed

2022-04-02 12:28 UTC, tuzi3040 approved these changes, later dismissed

2022-04-04 10:20 UTC, tuzi3040 requested changes

2022-04-04 10:20 UTC, tuzi3040 commented on src/06.anniv/08.meta.md
> +type TagType = "artist" | "group" | "animation" | "series" | "project" | "game" | "organization" | "default";
```suggestion
type TagType = "artist" | "group" | "animation" | "series" | "project" | "game" | "organization" | "category" | "default";
```

2022-04-04 10:29 UTC, tuzi3040 requested changes

2022-04-04 10:29 UTC, tuzi3040 commented on src/02.metadata-repository/06.metdata-db.md
> +  "tag_type"    TEXT NOT NULL DEFAULT 'default' CHECK("tag_type" IN ('artist', 'group', 'animation', 'series', 'project', 'game', 'organization', 'default'))
```suggestion
  "tag_type"    TEXT NOT NULL DEFAULT 'default' CHECK("tag_type" IN ('artist', 'group', 'animation', 'series', 'project', 'game', 'organization', 'category', 'default'))
```

2022-04-04 10:42 UTC, tuzi3040 approved these changes

2022-04-04 10:57 UTC, SeraphJACK approved these changes

2022-04-04 11:10 UTC, merged