Fix/types
ProjectAnni/book pull request #56
Opened 2022-04-18 07:09 UTC by Yesterday17

2022-04-18 09:20 UTC, SeraphJACK requested changes

2022-04-18 09:20 UTC, SeraphJACK commented on src/06.anniv/03.playlist.md
> +  | string // 封面图片链接
我其实比较反对引入外部链接

2022-04-18 09:37 UTC, Yesterday17 commented on src/06.anniv/03.playlist.md
> +  | string // 封面图片链接
但专辑封面确实不一定能完全满足播放列表的封面需求 :thinking:

不过首先可以先定义一下无封面的定义

2022-04-19 08:52 UTC, SeraphJACK approved these changes

2022-04-19 09:16 UTC, merged