[Breaking] 修改分享 Token 的创建方式
ProjectAnni/book pull request #57
Opened 2022-04-19 06:39 UTC by Yesterday17

2022-04-19 11:21 UTC, SeraphJACK requested changes

2022-04-19 11:21 UTC, SeraphJACK commented on src/05.audio-library/01.protocol.md
> +| `200`  | 成功获取音频 |
音频？

2022-05-06 15:25 UTC, SeraphJACK submitted a review, later dismissed

2022-05-10 02:57 UTC, SeraphJACK requested changes

2022-05-10 02:57 UTC, SeraphJACK commented on src/06.anniv/07.export-format.md
> +  disc_id: number;
直接继承 `DiscIdentifier` ？

2022-05-10 02:57 UTC, SeraphJACK commented on src/06.anniv/05.share.md
> +| `token`    | `ExportedPlaylistToken`    | 指定的 `Token`。当未指定时，由 `Anniv` 负责签发 `Token` |
Anniv 怎么知道用哪个 token 签呢（

2022-05-10 02:58 UTC, SeraphJACK commented
现在虽然有 controlled token 概念了，但 annil 没有标准化的签发用户 token 接口，没法和 anniv 对接。

2022-05-10 04:17 UTC, Yesterday17 commented on src/06.anniv/05.share.md
> +| `token`    | `ExportedPlaylistToken`    | 指定的 `Token`。当未指定时，由 `Anniv` 负责签发 `Token` |
加了个字段

2022-05-10 04:18 UTC, Yesterday17 commented
> 现在虽然有 controlled token 概念了，但 annil 没有标准化的签发用户 token 接口，没法和 anniv 对接。

不是有 `/admin/sign` 吗

2022-05-10 04:45 UTC, SeraphJACK approved these changes

2022-05-10 04:52 UTC, merged