Statistics
ProjectAnni/book pull request #67
Opened 2022-08-13 03:08 UTC by SeraphJACK

2022-08-13 04:57 UTC, Yesterday17 requested changes

2022-08-13 04:57 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +| `time`     | `timestamp` | 播放的时间戳          |
播放开始还是结束？要不要记录播放的进度？

2022-08-13 04:57 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +| `limit` | 获取历史播放条目数量上限，默认为 `10` |
是不是按时间区间取会比较好

2022-08-13 05:03 UTC, SeraphJACK commented on src/06.anniv/06.statistics.md
> +| `time`     | `timestamp` | 播放的时间戳          |
会有需要记录播放进度的需求吗

2022-08-13 05:06 UTC, SeraphJACK commented on src/06.anniv/06.statistics.md
> +| `limit` | 获取历史播放条目数量上限，默认为 `10` |
考虑客户端实现历史记录的功能，一般都是显示最近的几首而不是按照时间区间

2022-08-13 05:07 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +| `time`     | `timestamp` | 播放的时间戳          |
准确说是刚开始播放就切掉的话，是不是不应该算在播放里

2022-08-13 05:17 UTC, SeraphJACK commented on src/06.anniv/06.statistics.md
> +| `time`     | `timestamp` | 播放的时间戳          |
那这个应该放到客户端实现指导里面

2022-08-13 07:35 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +| `limit` | 获取历史播放条目数量上限，默认为 `10` |
不，一般要查的都是过去一段时间（比如一周）的播放次数吧，而不是准确的播放时间。单纯的历史记录没有太大意义吧

2022-08-13 14:06 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +  album_id: string;
`track: TrackIdentifier` ?

2022-08-13 14:06 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +| `start` | 统计区间开始时间 |
format

2022-08-13 14:06 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +`GET /api/statistics/self`
statistics 是不是有点长，stat 怎么样（

2022-08-13 14:06 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +  time: number;
```typescript
interface SongPlayRecord {
  track: TrackIdentifier,
  time: number;
}
```

2022-08-13 14:06 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +| `time`     | `timestamp` | 播放的时间戳          |
感觉 `time` 可能会歧义（s），要不改成 at？以及补充一下时间戳的单位

2022-08-13 14:06 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +## 获取当前用户播放记录
以及之后会不会有获取其他用户播放记录的api（？

2022-08-13 14:08 UTC, SeraphJACK commented on src/06.anniv/06.statistics.md
> +## 获取当前用户播放记录
太怪了（

2022-08-13 14:28 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +## 获取当前用户播放记录
想了一下，之后加个 user_id 的字段就行了

2022-08-16 12:16 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +`POST /api/stat`
突然想到，这里是不是应该弄成数组，比如离线放了很多需要一次提交上来

```ts
body: SongPlayRecord[]
```

```ts
interface SongPlayRecord {
  track: TrackIdentifier;
  at: number[];
}
```

2022-08-16 12:16 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +当用户播放时间过短时，不应该统计该次播放。
过短（如少于10秒，少于全曲的 1/3等）

2022-08-16 12:16 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +`GET /api/stat/self`
感觉没必要加这个 `/self`

2022-08-16 12:16 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +| `end`   | 统计区间结束时间戳（秒），默认为当前时间 |
当前时间 -> 请求提交时间

2022-08-16 12:16 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +若请求成功，返回 `SongPlayRecordResult[]` ，按照播放次数降序排序。
```suggestion
返回 `SongPlayRecordResult[]` ，按播放次数降序排序。
```

2022-08-16 12:16 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +`GET /api/stat/song`
感觉好像可以合并到 `/api/stat(/self)` 里？可能要权衡一下

2022-08-19 07:35 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +`GET /api/stat/song`
个人认为某一首曲的全服播放次数不大适合以任意查询的方式暴露给用户

2022-08-19 07:35 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +```
时间区间很大的话是不是这里要考虑分页？

2022-08-19 09:18 UTC, Last-Order commented on src/06.anniv/06.statistics.md
> +`GET /api/stat/song`
其实还行 spotify就默认展示
![image](https://user-images.githubusercontent.com/3362825/185587362-671c60ed-45a0-4de4-97b2-f70e569f1b91.png)

2022-08-31 16:16 UTC, Yesterday17 reviewed
应该就这几个问题

2022-08-31 16:16 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +  at: number[];
```suggestion
  // 播放开始的时间
  at: number[];
```

2022-08-31 16:16 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +当用户播放时间过短（如少于 10 秒，少于全曲的 1/3 等）时，不应该统计该次播放。
```suggestion
当用户播放时间过短（如少于 10 秒，少于全曲的 1/3 等，具体由播放器决定）时，不应该汇报本次播放。
```

2022-08-31 16:16 UTC, Yesterday17 commented on src/06.anniv/06.statistics.md
> +| `start` | 统计区间开始时间戳（秒）                     |
from, to 是不是更符合语义

2022-09-01 09:13 UTC, Yesterday17 approved these changes

2022-09-01 09:15 UTC, merged