Various fixes/features
ProjectAnni/book pull request #68
Opened 2022-08-13 03:18 UTC by SeraphJACK

- Add last_modified field in lyric response
- Add source field in lyric response
- Add last_modified field in playlist response
- Allow null PlaylistCover which tells the client cover should be the same as the first track of the playlist

2022-08-13 04:59 UTC, Yesterday17 requested changes

2022-08-13 04:59 UTC, Yesterday17 commented on src/06.anniv/03.playlist.md
> +  "last_modified": 1145141919810
好臭啊（x

2022-08-13 04:59 UTC, Yesterday17 commented on src/06.anniv/11.lyric.md
> +| `source`   | `string`                         | 歌词来源            |
加一个歌词最近更新？

2022-08-13 04:59 UTC, Yesterday17 commented on src/06.anniv/11.lyric.md
> +  type: "text" | "lrc" | "karaoke";
karaoke的格式？

2022-08-13 05:04 UTC, SeraphJACK commented on src/06.anniv/11.lyric.md
> +  type: "text" | "lrc" | "karaoke";
karaoke的格式？

2022-08-13 05:05 UTC, SeraphJACK commented on src/06.anniv/11.lyric.md
> +| `source`   | `string`                         | 歌词来源            |
这不是 POST 的表单吗

2022-08-13 05:05 UTC, SeraphJACK commented on src/06.anniv/11.lyric.md
> +| `source`   | `string`                         | 歌词来源            |
返回里面有的，修改表单里不应该有

2022-08-21 08:47 UTC, Yesterday17 commented on src/06.anniv/11.lyric.md
> +  type: "text" | "lrc" | "karaoke";
那我建议先不加 karaoke，后续 pr 再定（

2022-08-21 08:47 UTC, Yesterday17 commented on src/06.anniv/03.playlist.md
> +| `last_modified` | `number`                | 播放列表最后修改时间戳                                                |
单位为秒

2022-08-21 08:50 UTC, Yesterday17 requested changes

2022-08-21 08:50 UTC, Yesterday17 commented on src/06.anniv/11.lyric.md
> +| `901000` | 歌词修改无法写入，可能的原因有：修改 lrc 歌词为 text 歌词、修改 karaoke 歌词为其他歌词 |
这里还有 karaoke（

2022-08-21 08:52 UTC, Yesterday17 approved these changes

2022-08-21 08:52 UTC, merged