Favorite albums
ProjectAnni/book pull request #71
Opened 2022-09-21 05:23 UTC by SeraphJACK

2022-09-21 05:31 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +请求参数为一个 `AlbumIdentifier` 对象。
AlbumIdentifier 不是 object，是 string（

```suggestion
请求参数为 `AlbumIdentifier`。
```

2022-09-21 05:33 UTC, Yesterday17 requested changes

2022-09-21 05:33 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +### 添加专辑
```suggestion
### 添加专辑收藏
```

2022-09-21 05:33 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +### 获取喜欢专辑列表
```suggestion
### 获取收藏专辑列表
```

2022-09-21 05:33 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +返回 `AlbumInfo[]` ，按照添加时间倒序排序。
返回 AlbumInfo 多了接口是不是要炸）

2022-09-21 05:33 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +请求参数为一个 `AlbumIdentifier` 对象。
下同

2022-09-21 05:33 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +### 删除专辑
```suggestion
### 删除专辑收藏
```

2022-09-21 05:46 UTC, SeraphJACK commented on src/06.anniv/10.favorite.md
> +请求参数为一个 `AlbumIdentifier` 对象。
String 也可以有对象（

2022-09-21 05:47 UTC, SeraphJACK commented on src/06.anniv/10.favorite.md
> +返回 `AlbumInfo[]` ，按照添加时间倒序排序。
那只返回 intro ？还是 id ？

2022-09-25 13:54 UTC, Yesterday17 commented on src/06.anniv/10.favorite.md
> +请求参数为 `AlbumIdentifier`。
怎么请求，整个 body 代表 AlbumIdentifier 吗

2022-09-26 01:47 UTC, SeraphJACK commented on src/06.anniv/10.favorite.md
> +请求参数为 `AlbumIdentifier`。
JSON String literal

2022-09-26 02:54 UTC, Last-Order commented on src/06.anniv/10.favorite.md
> +请求参数为 `AlbumIdentifier`。
还是整个参数名吧 有点怪捏

2022-09-26 05:02 UTC, Yesterday17 approved these changes

2022-09-26 05:27 UTC, merged